train: ../train/images
val: ../valid/images
test: ../test/images

nc: 6
names: ['body', 'body_connector', 'gripper', 'leg', 'leg_connector', 'leg_marker']

roboflow:
  workspace: unitsassembly
  project: moonbot_v3
  version: 1
  license: MIT
  url: https://universe.roboflow.com/unitsassembly/moonbot_v3/dataset/1