# Controller manager configuration
/RF/controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    ### Controllers available
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController



### Properties of the controllers that we will use and definition of joints to use ###
# /RF/joint_state_broadcaster:
#   ros__parameters:
#     use_local_topics: true

/RF/forward_position_controller:
  ros__parameters:
    joints:
      - j_c1_rf
      - j_thigh_rf
      - j_tibia_rf

    interface_name: position


/RF/position_trajectory_controller:
  ros__parameters:
    joints:
      - j_c1_rf
      - j_thigh_rf
      - j_tibia_rf

    command_interfaces:
      - position

    state_interfaces:
      - position
      

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gain:
      j_c1_rf:
        p: 100.0
        i: 10.0
        d: 3600.0
      
      j_thigh_rf:
        p: 100.0
        i: 10.0
        d: 3600.0

      j_tibia_rf:
        p: 100.0
        i: 10.0
        d: 3600.0
